#The goal is to format and give general statistic descriptors of NOBO client information

In [1]:
import pandas as pd #Great for formatting and reimaging data
import numpy as np #Great for statistical functions
#Just a general cleanup of the data that should make things easier going forward. 
#Going to use this csv in another notebook to test some other things

In [6]:
df = pd.read_csv('NOBO_INFO_NEW.csv') #Read data into Pandas
df_copy = df.copy() #Making a copy incase

In [7]:
df.head() #Quick header to see they data I am working with.

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SORT:(D)ESCENDING (Z)IP CODE,NUMBER OF NOBOS,SHARES,1ST LINE OF NAME & ADDRESS,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,4TH LINE OF NAME & ADDRESS,5TH LINE OF NAME & ADDRESS,6TH LINE OF NAME & ADDRESS,7TH LINE OF NAME & ADDRESS,ZIP CODE FOR SORTING,CUSIP.1,# OF NOBOS,NUMBER OF SHARES
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323,D,244.0,300000,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,JAMESTOWN KY 42629-0080,,,,42629,491552S48,1,300000
1,I17079,491552S55,TURNPIKE AUTHORITY OF KENTUCKY,111323,D,NaN,250000,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,NaN,NaN,42102,491552S55,1,250000
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323,D,NaN,500000,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,BATON ROUGE LA 70809-7604,,,,70809,491552S63,2,750000
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323,D,NaN,250000,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,,,42102,491552S63,2,750000
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323,D,NaN,470000,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,,,,,90802,491552S71,4,1065000

In [8]:
columns_drop = ["SORT:(D)ESCENDING (Z)IP CODE", "NUMBER OF NOBOS","7TH LINE OF NAME & ADDRESS" ] #Taking out columns
df = df.drop(columns=columns_drop) # Drop these columns since they provide no relevant info

In [9]:
df.head() #Checking to see if it worked

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SHARES,1ST LINE OF NAME & ADDRESS,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,4TH LINE OF NAME & ADDRESS,5TH LINE OF NAME & ADDRESS,6TH LINE OF NAME & ADDRESS,ZIP CODE FOR SORTING,CUSIP.1,# OF NOBOS,NUMBER OF SHARES
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323,300000,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,JAMESTOWN KY 42629-0080,,,42629,491552S48,1,300000
1,I17079,491552S55,TURNPIKE AUTHORITY OF KENTUCKY,111323,250000,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,NaN,42102,491552S55,1,250000
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323,500000,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,BATON ROUGE LA 70809-7604,,,70809,491552S63,2,750000
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323,250000,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,,42102,491552S63,2,750000
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323,470000,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,,,,90802,491552S71,4,1065000

In [10]:
column_count = '6TH LINE OF NAME & ADDRESS' #Getting a count of the 6th line of name column
count_result = df[column_count].value_counts() #want a count because it's very empty
print(count_result)

6TH LINE OF NAME & ADDRESS
                                        229
CHICAGO IL                   60661        1
VIENNA             VA 22180-3550          1
BOWLING GREEN KY  42101-2250              1
HARTFORD      KY  42347-0070              1
PHOENIX AZ  85028                         1
KINGSLEY           MI 49649-9777          1
SHREVEPORT  LA  71106-6724                1
HOUSTON  TX  77095                        1
SAN ANTONIO TX               78258        1
DELRAY BEACH  FL  33483-5086              1
PALM BCH GDNS      FL 33410-1258          1
GA 30303-                                 1
BOCA RATON         FL 33428-0000          1
Name: count, dtype: int64

In [12]:
df = df.rename(columns={'1ST LINE OF NAME & ADDRESS': 'CLIENT'}) #Renaming for accuracy and easier to work with
df.head() #Always check my work

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SHARES,CLIENT,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,4TH LINE OF NAME & ADDRESS,5TH LINE OF NAME & ADDRESS,6TH LINE OF NAME & ADDRESS,ZIP CODE FOR SORTING,CUSIP.1,# OF NOBOS,NUMBER OF SHARES
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323,300000,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,JAMESTOWN KY 42629-0080,,,42629,491552S48,1,300000
1,I17079,491552S55,TURNPIKE AUTHORITY OF KENTUCKY,111323,250000,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,NaN,42102,491552S55,1,250000
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323,500000,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,BATON ROUGE LA 70809-7604,,,70809,491552S63,2,750000
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323,250000,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,,42102,491552S63,2,750000
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323,470000,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,,,,90802,491552S71,4,1065000

In [15]:
df['Inv_type'] = 'Other'  # Default value, if it doesn't meet criteria then will be other
# Define rules to categorize based on keywords, had to look through some of the file
df.loc[(df['CLIENT'].str.contains('FUND|COUNTY|CITY', case=False)) | (df['2ND LINE OF NAME & ADDRESS'].str.contains('FUND|COUNTY|CITY', case=False)), 'Inv_type'] = 'Bond Fund'
df.loc[(df['CLIENT'].str.contains('INSURANCE|ASSURANCE|KSKJ|HEALTH|NATIONWIDE', case=False)) | (df['2ND LINE OF NAME & ADDRESS'].str.contains('INSURANCE|ASSURANCE|KSKJ|HEALTH|NATIONWIDE', case=False)), 'Inv_type'] = 'Insurance Company'
df.loc[(df['CLIENT'].str.contains('INVESTMENT|INVESTING|CAPITAL|TRUST|WEALTH|SECURITIES', case=False)) | (df['2ND LINE OF NAME & ADDRESS'].str.contains('INVESTMENT|INVESTING|CAPITAL|TRUST|WEALTH|SECURITIES', case=False)), 'Inv_type'] = 'Investment Firm'
df.loc[(df['CLIENT'].str.contains('RETAIL|BANK|IRA|SCHWAB', case=False)) | (df['2ND LINE OF NAME & ADDRESS'].str.contains('RETAIL|BANK|IRA|SCHWAB', case=False)), 'Inv_type'] = 'Retail'
# check work, this is probably where it could get classification wrong because it searches based on the keywords
print(df[['CLIENT', '2ND LINE OF NAME & ADDRESS', 'Inv_type']])

                                   CLIENT  \
0    CUMBERLAND CELLULAR LLC
1    CITY OF BOWLING GREEN GENERAL
2    28501 FIRST NATIONAL BANKER'S BANK
3    CITY OF BOWLING GREEN GENERAL
4    BRUCE PARKS
..                                    ...
239  PAULA FRANCES PAYNE (IRA)
240  STIFEL BANK CUSTODIAN FOR
241  JOSEPH DAMBRUOSO
242  HARVEY CAPITAL MANAGEMENT
243  VIRGINIA M DAMBRUOSO

               2ND LINE OF NAME & ADDRESS         Inv_type
0    ATTN DARYL L HAMMOND                            Other
1    FUND                                        Bond Fund
2    ATTN: CAPITAL MARKETS                          Retail
3    FUND                                        Bond Fund
4    200 OCEANGATE  SUITE3V 100                      Other
..                                    ...              ...
239  WFCS AS CUSTODIAN                              Retail
240  CAROLE W REED BENE                             Retail
241  18 PINE VIEW DRIVE                              Other
242  400 ROYAL PALM WAY                    Investment Firm
243  18 PINE VIEW DRIVE                              Other

[244 rows x 3 columns]

In [16]:
df.head()

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SHARES,CLIENT,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,4TH LINE OF NAME & ADDRESS,5TH LINE OF NAME & ADDRESS,6TH LINE OF NAME & ADDRESS,ZIP CODE FOR SORTING,CUSIP.1,# OF NOBOS,NUMBER OF SHARES,Inv_type
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323,300000,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,JAMESTOWN KY 42629-0080,,,42629,491552S48,1,300000,Other
1,I17079,491552S55,TURNPIKE AUTHORITY OF KENTUCKY,111323,250000,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,NaN,42102,491552S55,1,250000,Bond Fund
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323,500000,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,BATON ROUGE LA 70809-7604,,,70809,491552S63,2,750000,Retail
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323,250000,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,,42102,491552S63,2,750000,Bond Fund
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323,470000,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,,,,90802,491552S71,4,1065000,Other

In [29]:
#Goal of this is to remove '6th line of name & address' and combine the data into the previous column, less columns is better
df.loc[:, 'COMBINED ADDRESS'] = df['5TH LINE OF NAME & ADDRESS'].astype(str) + ' ' + df['6TH LINE OF NAME & ADDRESS'].astype(str)
#drop any missing data values, loc is important because it keeps the data in the same shape
df = df.dropna(subset=['6TH LINE OF NAME & ADDRESS'])

In [30]:
df #check the dataframe

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SHARES,CLIENT,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,4TH LINE OF NAME & ADDRESS,5TH LINE OF NAME & ADDRESS,6TH LINE OF NAME & ADDRESS,ZIP CODE FOR SORTING,CUSIP.1,# OF NOBOS,NUMBER OF SHARES,Inv_type,COMBINED ADDRESS
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,300000.0,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,JAMESTOWN KY 42629-0080,,,42629.0,491552S48,1.0,300000.0,Other,...
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,500000.0,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,BATON ROUGE LA 70809-7604,,,70809.0,491552S63,2.0,750000.0,Retail,...
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,250000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,,42102.0,491552S63,2.0,750000.0,Bond Fund,BOWLING GREEN KY 42102-0430 ...
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,470000.0,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,,,,90802.0,491552S71,4.0,1065000.0,Other,...
5,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,295000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,,42102.0,491552S71,4.0,1065000.0,Bond Fund,BOWLING GREEN KY 42102-0430 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,PAULA FRANCES PAYNE (IRA),WFCS AS CUSTODIAN,FIXED INC,1207 BROOKFIELD CT,HIGH POINT NC 27262-7443,,27262.0,491552UZ6,40.0,41295000.0,Retail,HIGH POINT NC 27262-7443 ...
240,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,STIFEL BANK CUSTODIAN FOR,CAROLE W REED BENE,OSCAR WEISS DECD IRA,PO BOX 205,HEMLOCK NY 14466-0205,,14466.0,491552UZ6,40.0,41295000.0,Retail,HEMLOCK NY 14466-0205 ...
241,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,JOSEPH DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,,,,6512.0,491552UZ6,40.0,41295000.0,Other,...
242,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,HARVEY CAPITAL MANAGEMENT,400 ROYAL PALM WAY,SUITE 400,PALM BEACH FL 33480,,,33480.0,491552UZ6,40.0,41295000.0,Investment Firm,...
243,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,5000.0,VIRGINIA M DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,,,,6512.0,491552UZ6,40.0,41295000.0,Other,...

In [31]:
df.loc[:, 'COMBINED ADDRESS'] = df['4TH LINE OF NAME & ADDRESS'].astype(str) + ' ' + df['COMBINED ADDRESS'].astype(str)
#Trying to do the same with the previous column

In [32]:
df

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SHARES,CLIENT,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,4TH LINE OF NAME & ADDRESS,5TH LINE OF NAME & ADDRESS,6TH LINE OF NAME & ADDRESS,ZIP CODE FOR SORTING,CUSIP.1,# OF NOBOS,NUMBER OF SHARES,Inv_type,COMBINED ADDRESS
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,300000.0,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,JAMESTOWN KY 42629-0080,,,42629.0,491552S48,1.0,300000.0,Other,JAMESTOWN KY 42629-0080 ...
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,500000.0,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,BATON ROUGE LA 70809-7604,,,70809.0,491552S63,2.0,750000.0,Retail,BATON ROUGE LA 70809-7604 ...
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,250000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,,42102.0,491552S63,2.0,750000.0,Bond Fund,PO BOX 430 BOWLING G...
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,470000.0,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,,,,90802.0,491552S71,4.0,1065000.0,Other,...
5,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,295000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,PO BOX 430,BOWLING GREEN KY 42102-0430,,42102.0,491552S71,4.0,1065000.0,Bond Fund,PO BOX 430 BOWLING G...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,PAULA FRANCES PAYNE (IRA),WFCS AS CUSTODIAN,FIXED INC,1207 BROOKFIELD CT,HIGH POINT NC 27262-7443,,27262.0,491552UZ6,40.0,41295000.0,Retail,1207 BROOKFIELD CT HIGH POIN...
240,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,STIFEL BANK CUSTODIAN FOR,CAROLE W REED BENE,OSCAR WEISS DECD IRA,PO BOX 205,HEMLOCK NY 14466-0205,,14466.0,491552UZ6,40.0,41295000.0,Retail,PO BOX 205 HEMLOCK N...
241,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,JOSEPH DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,,,,6512.0,491552UZ6,40.0,41295000.0,Other,...
242,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,HARVEY CAPITAL MANAGEMENT,400 ROYAL PALM WAY,SUITE 400,PALM BEACH FL 33480,,,33480.0,491552UZ6,40.0,41295000.0,Investment Firm,PALM BEACH FL 33480 ...
243,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,5000.0,VIRGINIA M DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,,,,6512.0,491552UZ6,40.0,41295000.0,Other,...

In [36]:
columns_to_drop = ['4TH LINE OF NAME & ADDRESS', '5TH LINE OF NAME & ADDRESS', '6TH LINE OF NAME & ADDRESS'] #bye columns
df = df.drop(columns=columns_to_drop)

KeyError: "['4TH LINE OF NAME & ADDRESS', '5TH LINE OF NAME & ADDRESS', '6TH LINE OF NAME & ADDRESS'] not found in axis"

In [40]:
# Find the index of the 'Inv_type' column
inv_type_index = df.columns.get_loc('Inv_type') #Want the new column to be moved 
new_position = 8
df.insert(new_position, 'Inv_type', df.pop('Inv_type')) # Move the 'Inv_type' column to the new position

In [41]:
df

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SHARES,CLIENT,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,Inv_type,ZIP CODE FOR SORTING,CUSIP.1,# OF NOBOS,NUMBER OF SHARES,COMBINED ADDRESS
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,300000.0,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,Other,42629.0,491552S48,1.0,300000.0,JAMESTOWN KY 42629-0080 ...
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,500000.0,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,Retail,70809.0,491552S63,2.0,750000.0,BATON ROUGE LA 70809-7604 ...
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,250000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,Bond Fund,42102.0,491552S63,2.0,750000.0,PO BOX 430 BOWLING G...
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,470000.0,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,Other,90802.0,491552S71,4.0,1065000.0,...
5,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,295000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,Bond Fund,42102.0,491552S71,4.0,1065000.0,PO BOX 430 BOWLING G...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,PAULA FRANCES PAYNE (IRA),WFCS AS CUSTODIAN,FIXED INC,Retail,27262.0,491552UZ6,40.0,41295000.0,1207 BROOKFIELD CT HIGH POIN...
240,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,STIFEL BANK CUSTODIAN FOR,CAROLE W REED BENE,OSCAR WEISS DECD IRA,Retail,14466.0,491552UZ6,40.0,41295000.0,PO BOX 205 HEMLOCK N...
241,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,JOSEPH DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,Other,6512.0,491552UZ6,40.0,41295000.0,...
242,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,HARVEY CAPITAL MANAGEMENT,400 ROYAL PALM WAY,SUITE 400,Investment Firm,33480.0,491552UZ6,40.0,41295000.0,PALM BEACH FL 33480 ...
243,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,5000.0,VIRGINIA M DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,Other,6512.0,491552UZ6,40.0,41295000.0,...

In [42]:
columns_to_drops = ['CUSIP.1'] #bye columns, this was a duplicate column
df = df.drop(columns=columns_to_drops) #should have removed them earlier but got error since itn't there anymore
df

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SHARES,CLIENT,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,Inv_type,ZIP CODE FOR SORTING,# OF NOBOS,NUMBER OF SHARES,COMBINED ADDRESS
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,300000.0,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,Other,42629.0,1.0,300000.0,JAMESTOWN KY 42629-0080 ...
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,500000.0,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,Retail,70809.0,2.0,750000.0,BATON ROUGE LA 70809-7604 ...
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,250000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,Bond Fund,42102.0,2.0,750000.0,PO BOX 430 BOWLING G...
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,470000.0,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,Other,90802.0,4.0,1065000.0,...
5,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,295000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,Bond Fund,42102.0,4.0,1065000.0,PO BOX 430 BOWLING G...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,PAULA FRANCES PAYNE (IRA),WFCS AS CUSTODIAN,FIXED INC,Retail,27262.0,40.0,41295000.0,1207 BROOKFIELD CT HIGH POIN...
240,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,STIFEL BANK CUSTODIAN FOR,CAROLE W REED BENE,OSCAR WEISS DECD IRA,Retail,14466.0,40.0,41295000.0,PO BOX 205 HEMLOCK N...
241,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,JOSEPH DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,Other,6512.0,40.0,41295000.0,...
242,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,HARVEY CAPITAL MANAGEMENT,400 ROYAL PALM WAY,SUITE 400,Investment Firm,33480.0,40.0,41295000.0,PALM BEACH FL 33480 ...
243,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,5000.0,VIRGINIA M DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,Other,6512.0,40.0,41295000.0,...

In [46]:
#try to add some of the address data from "3rd" to the combined address without adding non-address data
condition = df['3RD LINE OF NAME & ADDRESS'].str.strip().str.contains('\d', na=False)
df['COMBINED ADDRESS'] = np.where(condition, df['COMBINED ADDRESS'].astype(str) + ' ' + df['3RD LINE OF NAME & ADDRESS'].fillna('').astype(str), df['COMBINED ADDRESS'])

In [50]:
df

,JOB NUMBER,CUSIP,ISSUER NAME,RECORD DATE,SHARES,CLIENT,2ND LINE OF NAME & ADDRESS,3RD LINE OF NAME & ADDRESS,Inv_type,ZIP CODE FOR SORTING,# OF NOBOS,NUMBER OF SHARES,COMBINED ADDRESS
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,300000.0,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,Other,42629.0,1.0,300000.0,JAMESTOWN KY 42629-0080 ...
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,500000.0,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,Retail,70809.0,2.0,750000.0,BATON ROUGE LA 70809-7604 ...
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,250000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,Bond Fund,42102.0,2.0,750000.0,PO BOX 430 BOWLING G...
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,470000.0,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,Other,90802.0,4.0,1065000.0,...
5,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,295000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,Bond Fund,42102.0,4.0,1065000.0,PO BOX 430 BOWLING G...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,PAULA FRANCES PAYNE (IRA),WFCS AS CUSTODIAN,FIXED INC,Retail,27262.0,40.0,41295000.0,1207 BROOKFIELD CT HIGH POIN...
240,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,STIFEL BANK CUSTODIAN FOR,CAROLE W REED BENE,OSCAR WEISS DECD IRA,Retail,14466.0,40.0,41295000.0,PO BOX 205 HEMLOCK N...
241,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,JOSEPH DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,Other,6512.0,40.0,41295000.0,...
242,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,HARVEY CAPITAL MANAGEMENT,400 ROYAL PALM WAY,SUITE 400,Investment Firm,33480.0,40.0,41295000.0,PALM BEACH FL 33480 ...
243,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,5000.0,VIRGINIA M DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,Other,6512.0,40.0,41295000.0,...

In [59]:
df = df.rename(columns={
    'COMBINED ADDRESS': 'ADDRESS',
    'ZIP CODE FOR SORTING': 'ZIP CODE',
    'NUMBER OF SHARES': 'TOTAL SHARES',
    'ISSUER NAME': 'ISSUER',
    'Inv_type': 'CLASSIFICATION',
    'RECORD DATE': 'DATE',
    '2ND LINE OF NAME & ADDRESS': 'CONTACT/ADDRESS',
    '3RD LINE OF NAME & ADDRESS': 'FULL ADDRESS'
})
#rename columns since it is easier to work with and more practical

In [60]:
df

,JOB NUMBER,CUSIP,ISSUER,DATE,SHARES,CLIENT,CONTACT/ADDRESS,FULL ADDRESS,CLASSIFICATION,ZIP CODE,# OF NOBOS,TOTAL SHARES,ADDRESS
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,300000.0,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80,Other,42629.0,1.0,300000.0,JAMESTOWN KY 42629-0080 ...
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,500000.0,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD,Retail,70809.0,2.0,750000.0,BATON ROUGE LA 70809-7604 ...
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,250000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,Bond Fund,42102.0,2.0,750000.0,PO BOX 430 BOWLING G...
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,470000.0,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802,Other,90802.0,4.0,1065000.0,...
5,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,295000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD,Bond Fund,42102.0,4.0,1065000.0,PO BOX 430 BOWLING G...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,PAULA FRANCES PAYNE (IRA),WFCS AS CUSTODIAN,FIXED INC,Retail,27262.0,40.0,41295000.0,1207 BROOKFIELD CT HIGH POIN...
240,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,STIFEL BANK CUSTODIAN FOR,CAROLE W REED BENE,OSCAR WEISS DECD IRA,Retail,14466.0,40.0,41295000.0,PO BOX 205 HEMLOCK N...
241,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,JOSEPH DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,Other,6512.0,40.0,41295000.0,...
242,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,10000.0,HARVEY CAPITAL MANAGEMENT,400 ROYAL PALM WAY,SUITE 400,Investment Firm,33480.0,40.0,41295000.0,PALM BEACH FL 33480 ...
243,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,111323.0,5000.0,VIRGINIA M DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220,Other,6512.0,40.0,41295000.0,...

In [67]:
df['ADDRESS'] = df['FULL ADDRESS'].fillna('') + ' ' + df['ADDRESS'].fillna('') #change full address to address
df.insert(7, 'ADDRESS', df.pop('ADDRESS')) #Move it into a different position
df.drop('FULL ADDRESS', axis=1, inplace=True) #Drop the Full address column since it was replaced by address column

KeyError: 'FULL ADDRESS'

In [69]:
df.drop('DATE', axis=1, inplace=True) #Also dropped date column since it didn't have useable info, all the same (111323)
df

,JOB NUMBER,CUSIP,ISSUER,SHARES,CLIENT,CONTACT/ADDRESS,ADDRESS,CLASSIFICATION,ZIP CODE,# OF NOBOS,TOTAL SHARES
0,I17079,491552S48,TURNPIKE AUTHORITY OF KENTUCKY,300000.0,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80 PO BOX 80...,Other,42629.0,1.0,300000.0
2,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,500000.0,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD 7813 OFFI...,Retail,70809.0,2.0,750000.0
3,I17079,491552S63,TURNPIKE AUTHORITY OF KENTUCKY,250000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD ATTN KATI...,Bond Fund,42102.0,2.0,750000.0
4,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,470000.0,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802 LONG BEAC...,Other,90802.0,4.0,1065000.0
5,I17079,491552S71,TURNPIKE AUTHORITY OF KENTUCKY,295000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD ATTN KATI...,Bond Fund,42102.0,4.0,1065000.0
...,...,...,...,...,...,...,...,...,...,...,...
239,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,10000.0,PAULA FRANCES PAYNE (IRA),WFCS AS CUSTODIAN,FIXED INC FIXED INC...,Retail,27262.0,40.0,41295000.0
240,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,10000.0,STIFEL BANK CUSTODIAN FOR,CAROLE W REED BENE,OSCAR WEISS DECD IRA OSCAR WEI...,Retail,14466.0,40.0,41295000.0
241,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,10000.0,JOSEPH DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220 EAST HAVE...,Other,6512.0,40.0,41295000.0
242,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,10000.0,HARVEY CAPITAL MANAGEMENT,400 ROYAL PALM WAY,SUITE 400 SUITE 400...,Investment Firm,33480.0,40.0,41295000.0
243,I17079,491552UZ6,TURNPIKE AUTHORITY OF KENTUCKY,5000.0,VIRGINIA M DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220 EAST HAVE...,Other,6512.0,40.0,41295000.0

In [70]:
df.drop('ISSUER', axis=1, inplace=True) #Dropped issuer since all the same and will allow it to proccess quicker
df

,JOB NUMBER,CUSIP,SHARES,CLIENT,CONTACT/ADDRESS,ADDRESS,CLASSIFICATION,ZIP CODE,# OF NOBOS,TOTAL SHARES
0,I17079,491552S48,300000.0,CUMBERLAND CELLULAR LLC,ATTN DARYL L HAMMOND,PO BOX 80 PO BOX 80...,Other,42629.0,1.0,300000.0
2,I17079,491552S63,500000.0,28501 FIRST NATIONAL BANKER'S BANK,ATTN: CAPITAL MARKETS,7813 OFFICE PARK BLVD 7813 OFFI...,Retail,70809.0,2.0,750000.0
3,I17079,491552S63,250000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD ATTN KATI...,Bond Fund,42102.0,2.0,750000.0
4,I17079,491552S71,470000.0,BRUCE PARKS,200 OCEANGATE SUITE3V 100,LONG BEACH CA 90802 LONG BEAC...,Other,90802.0,4.0,1065000.0
5,I17079,491552S71,295000.0,CITY OF BOWLING GREEN GENERAL,FUND,ATTN KATIE E SCHALLER-WARD ATTN KATI...,Bond Fund,42102.0,4.0,1065000.0
...,...,...,...,...,...,...,...,...,...,...
239,I17079,491552UZ6,10000.0,PAULA FRANCES PAYNE (IRA),WFCS AS CUSTODIAN,FIXED INC FIXED INC...,Retail,27262.0,40.0,41295000.0
240,I17079,491552UZ6,10000.0,STIFEL BANK CUSTODIAN FOR,CAROLE W REED BENE,OSCAR WEISS DECD IRA OSCAR WEI...,Retail,14466.0,40.0,41295000.0
241,I17079,491552UZ6,10000.0,JOSEPH DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220 EAST HAVE...,Other,6512.0,40.0,41295000.0
242,I17079,491552UZ6,10000.0,HARVEY CAPITAL MANAGEMENT,400 ROYAL PALM WAY,SUITE 400 SUITE 400...,Investment Firm,33480.0,40.0,41295000.0
243,I17079,491552UZ6,5000.0,VIRGINIA M DAMBRUOSO,18 PINE VIEW DRIVE,EAST HAVEN CT 06512-1220 EAST HAVE...,Other,6512.0,40.0,41295000.0

In [77]:
# changing around the columns for swag
df = df[['JOB NUMBER','CUSIP', 'CLIENT', 'CLASSIFICATION','SHARES', 'TOTAL SHARES' ,'CONTACT/ADDRESS', 'ADDRESS', 'ZIP CODE', '# OF NOBOS']]
df

KeyError: "['# OF NOBOS'] not in index"

In [76]:
#So going to create this csv to try and add a state column in a seperate notebook so I don't mess with this
#Ignore the errors as these were created after I already got the desired results but re-ran my code to test
df.to_csv(r'U:\Python\NOBO\NOBO_Cleaned.csv', index=False)